add some test and init
VargaJoe/sn-miniapp-tasklist pull request #7
Opened 2019-11-18 12:40 UTC by blaskodaniel

2019-11-19 14:12 UTC, zoltanbedi requested changes

2019-11-19 14:12 UTC, zoltanbedi commented on src/app.tsx
>    // const usr = useCurrentUser()
```suggestion
```

2019-11-19 14:12 UTC, zoltanbedi commented on src/app.tsx
>    // const repo = useRepository()
```suggestion
```

2019-11-19 14:12 UTC, zoltanbedi commented on src/components/list-panel.tsx
> +    const newStatus =
```suggestion
    const newStatus = task.Status?.[0] === Status.completed ? [Status.active] : [Status.completed]
```
With typescript 3.7 you can write it like this.

2019-11-19 14:12 UTC, zoltanbedi commented on src/components/list-panel.tsx
> +      typeof task.Status !== 'undefined' && task.Status[0] === Status.completed ? [Status.active] : [Status.completed]
```suggestion
```

2019-11-19 14:12 UTC, zoltanbedi commented on src/components/list-panel.tsx
> +    const classCompleted = typeof d.Status !== 'undefined' && d.Status[0] === Status.completed ? 'comp' : ''
Same here. Please use conditional operator.

2019-11-19 14:12 UTC, zoltanbedi commented on src/components/list-panel.tsx
> +            checked={typeof d.Status !== 'undefined' && d.Status[0] == Status.completed}
Same.

2019-11-20 09:26 UTC, blaskodaniel commented on src/components/list-panel.tsx
> +            checked={typeof d.Status !== 'undefined' && d.Status[0] == Status.completed}
fixed

2019-11-20 09:27 UTC, blaskodaniel commented on src/components/list-panel.tsx
> +    const classCompleted = typeof d.Status !== 'undefined' && d.Status[0] === Status.completed ? 'comp' : ''
fixed

2019-11-20 10:02 UTC, zoltanbedi approved these changes
🦸‍♂️

2019-11-20 10:04 UTC, merged